# Generated by Django 3.2 on 2021-12-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
